=== Korman2018/intLab_lesson03_XML/store.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="store">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="categories" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="category" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="subcategories">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="subcategory" maxOccurs="unbounded" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="products" maxOccurs="unbounded"
                                                                            minOccurs="0">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="product"
                                                                                        maxOccurs="unbounded"
                                                                                        minOccurs="0">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element
                                                                                                name="manufacturerName">
                                                                                            <xs:simpleType>
                                                                                                <xs:restriction
                                                                                                        base="xs:string">
                                                                                                    <xs:pattern
                                                                                                            value="[A-Za-z]*"/>
                                                                                                </xs:restriction>
                                                                                            </xs:simpleType>
                                                                                        </xs:element>
                                                                                        <xs:element name="model">
                                                                                            <xs:simpleType>
                                                                                                <xs:restriction
                                                                                                        base="xs:string">
                                                                                                    <xs:pattern
                                                                                                            value="[A-Za-z]{2}[0-9]{3}"/>
                                                                                                </xs:restriction>
                                                                                            </xs:simpleType>
                                                                                        </xs:element>
                                                                                        <xs:element
                                                                                                name="manufactureDate">
                                                                                            <xs:simpleType>
                                                                                                <xs:restriction
                                                                                                        base="xs:string">
                                                                                                    <xs:pattern
                                                                                                            value="(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[012])-[0-9]{4}"/>
                                                                                                </xs:restriction>
                                                                                            </xs:simpleType>
                                                                                        </xs:element>
                                                                                        <xs:element name="color">
                                                                                            <xs:simpleType>
                                                                                                <xs:restriction
                                                                                                        base="xs:string">
                                                                                                    <xs:enumeration
                                                                                                            value="BLACK"/>
                                                                                                    <xs:enumeration
                                                                                                            value="WHITE"/>
                                                                                                    <xs:enumeration
                                                                                                            value="NONE"/>
                                                                                                    <xs:enumeration
                                                                                                            value="RED"/>
                                                                                                    <xs:enumeration
                                                                                                            value="OTHER"/>
                                                                                                </xs:restriction>
                                                                                            </xs:simpleType>
                                                                                        </xs:element>
                                                                                        <xs:element name="price">
                                                                                            <xs:simpleType>
                                                                                                <xs:restriction
                                                                                                        base="xs:double">
                                                                                                    <xs:minInclusive
                                                                                                            value="0"/>
                                                                                                </xs:restriction>
                                                                                            </xs:simpleType>
                                                                                        </xs:element>
                                                                                        <xs:element name="amount">
                                                                                            <xs:simpleType>
                                                                                                <xs:restriction
                                                                                                        base="xs:integer">
                                                                                                    <xs:minInclusive
                                                                                                            value="0"/>
                                                                                                </xs:restriction>
                                                                                            </xs:simpleType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute type="xs:string" name="name" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Korman2018/intLab_lesson03_XML/source.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='store.xsd'>
    <categories>
        <category name="components">
            <subcategories>
                <subcategory name="mouses">
                    <products>
                        <product>
                            <manufacturerName>Genius</manufacturerName>
                            <model>GL202</model>
                            <manufactureDate>21-11-2018</manufactureDate>
                            <color>BLACK</color>
                            <price>700.0</price>
                            <amount>10</amount>
                        </product>
                        <product>
                            <manufacturerName>Genius</manufacturerName>
                            <model>GO210</model>
                            <manufactureDate>21-11-2018</manufactureDate>
                            <color>WHITE</color>
                            <price>900.0</price>
                            <amount>1</amount>
                        </product>
                        <product>
                            <manufacturerName>Logitech</manufacturerName>
                            <model>LO707</model>
                            <manufactureDate>21-11-2018</manufactureDate>
                            <color>BLACK</color>
                            <price>1200.0</price>
                            <amount>3</amount>
                        </product>
                    </products>
                </subcategory>
                <subcategory name="processors">
                    <products>
                        <product>
                            <manufacturerName>Intel</manufacturerName>
                            <model>IC588</model>
                            <manufactureDate>12-12-2018</manufactureDate>
                            <color>NONE</color>
                            <price>15800.0</price>
                            <amount>3</amount>
                        </product>
                        <product>
                            <manufacturerName>AMD</manufacturerName>
                            <model>AA760</model>
                            <manufactureDate>01-09-2018</manufactureDate>
                            <color>NONE</color>
                            <price>13445.50</price>
                            <amount>1</amount>
                        </product>
                    </products>
                </subcategory>
            </subcategories>
        </category>
        <category name="computersAndMonitors">
            <subcategories>
                <subcategory name="monitors">
                    <products>
                        <product>
                            <manufacturerName>LG</manufacturerName>
                            <model>LL233</model>
                            <manufactureDate>21-11-2018</manufactureDate>
                            <color>BLACK</color>
                            <price>7700.0</price>
                            <amount>5</amount>
                        </product>
                        <product>
                            <manufacturerName>Samsung</manufacturerName>
                            <model>SL240</model>
                            <manufactureDate>21-11-2018</manufactureDate>
                            <color>WHITE</color>
                            <price>9780.0</price>
                            <amount>1</amount>
                        </product>
                    </products>
                </subcategory>
            </subcategories>
        </category>
    </categories>
</store>
